# Generated by Django 6.0.2 on 2026-02-18 17:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftRegistryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo_url', models.CharField(max_length=500)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('is_claimed', models.BooleanField(default=False)),
                ('claimed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Gift Registry Item',
                'verbose_name_plural': 'Gift Registry Items',
                'db_table': 'gift_registry',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('attending', models.BooleanField(default=True)),
                ('number_of_guests', models.IntegerField(default=1)),
                ('food_intolerances', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RSVP',
                'verbose_name_plural': 'RSVPs',
                'db_table': 'rsvps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Wish',
                'verbose_name_plural': 'Wishes',
                'db_table': 'wishes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RSVPGuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=255)),
                ('guest_order', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rsvp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_guests', to='wedding.rsvp')),
            ],
            options={
                'verbose_name': 'Additional Guest',
                'verbose_name_plural': 'Additional Guests',
                'db_table': 'rsvp_guests',
                'ordering': ['guest_order'],
            },
        ),
    ]
