# Generated by Django 6.0.2 on 2026-02-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftregistryitem',
            name='photo_image',
            field=models.ImageField(blank=True, help_text='Upload an image file', null=True, upload_to='gift_images/'),
        ),
        migrations.AlterField(
            model_name='giftregistryitem',
            name='photo_url',
            field=models.CharField(blank=True, help_text='Or provide an external image URL', max_length=500, null=True),
        ),
    ]
